#! /bin/sh

# To start the daemon in the background
sxhkd &
picom &

# kill previously running instances of polybar
xfce4-panel &

feh --bg-fill --randomize ~/Pictures/* &


bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width            2.0
bspc config focused_border_color 	\#FEFEFE
bspc config normal_border_color 	\#111824
bspc config window_gap              12
bspc config border_radius           15
bspc config top_padding 35
bspc config bottom_padding 12
bspc config left_padding 12
bspc config right_padding 12



bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config single_monocle	        true



bspc rule -a firefox desktop='^3'  
bspc rule -a code desktop='^1' 




#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
